app:
 image: jaequery/honeybadger
 links:
 - db:postgresdb
 - memcache:memcache
 command: /app/bin/docker/init.sh
 environment:
 - VIRTUAL_HOST=honeybadger.docker
 - RACK_ENV=development
 - BUNDLE_PATH=/app/volumes/bundler
 - PASSENGER_POOL_IDLE_TIME=0 
 volumes:
 - .:/app
 #tty: true
 #restart: always 

db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=changeme
 - POSTGRES_DB=honeybadger_development
 volumes:
# - honeybadgerdb:/var/lib/postgresql/data 
 - ./sql:/sql
 ports:
 - "5432"
 #restart: always

memcache:
 image: memcached
 ports:
 - "11211"

# mongo:
#  image: mongo
#  ports:
#  - "27017:27017"
